apiVersion: v1
name: autocert
version: 0.1.0
appVersion: 0.11.0-rc.2
description: A kubernetes add-on that automatically injects TLS/HTTPS certificates into your containers.
keywords:
 - ca
 - tls
 - pki
 - step
 - step-ca
 - step-certificates
 - smallstep
 - certificate
 - certificates
 - authority
home: https://smallstep.com
icon: https://raw.githubusercontent.com/smallstep/autocert/master/icon.png
sources:
 - https://github.com/smallstep/autocert
maintainers:
 - name: maraino
   email: mariano@smallstep.com
engine: gotpl
