apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "autocert.fullname" . }}
  labels: 
    {{- include "autocert.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "autocert.fullname" . }}
  labels: 
    {{- include "autocert.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "autocert.fullname" . }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
