apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "step-ca.fullname" . }}
  labels:
{{ include "step-ca.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "step-ca.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "step-ca.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{- if .Release.IsInstall }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          image: busybox:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sleep", "5"]
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/step-ca", 
            "--password-file", "/home/step/secrets/passwords/password",
            "/home/step/config/ca.json"]
          env:
          - name: NAMESPACE
            value: "{{ .Release.Namespace }}"
          ports:
            - name: https
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
              scheme: HTTPS
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: certs
            mountPath: /home/step/certs
            readOnly: true
          - name: config
            mountPath: /home/step/config
            readOnly: true
          - name: secrets
            mountPath: /home/step/secrets
            readOnly: true
          - name: ca-password
            mountPath: /home/step/secrets/passwords
            readOnly: true
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
      volumes:
      - name: certs
        configMap:
          name: {{ include "step-ca.fullname" . }}-certs
      - name: config
        configMap:
          name: {{ include "step-ca.fullname" . }}-config
      - name: secrets
        configMap:
          name: {{ include "step-ca.fullname" . }}-secrets
      - name: ca-password
        secret:
          secretName: {{ include "step-ca.fullname" . }}-ca-password
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
