# Secrets that will be updated by the configuration job: 
# 1. CA keys password.
# 2. Provisioner password.
apiVersion: v1
data:
  password: ""
kind: Secret
metadata:
  name: {{ include "step-ca.fullname" . }}-ca-password
  namespace: {{.Release.Namespace}}
---
apiVersion: v1
data:
  password: ""
kind: Secret
metadata:
  name: {{ include "step-ca.fullname" . }}-provisioner-password
  namespace: {{.Release.Namespace}}
