apiVersion: v1
kind: Service
metadata:
  name: {{ include "step-certificates.fullname" . }}
  labels:
    {{- include "step-certificates.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "step-certificates.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
