apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "step-issuer.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: {{ .Values.service.controlPlane }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: {{ .Values.service.controlPlane }}
  template:
    metadata:
      labels:
        control-plane: {{ .Values.service.controlPlane }}
    spec:
      {{- if $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range $key := $.Values.imagePullSecrets }}
        - name: {{ $key }}
        {{- end }}
      {{- end }}
      containers:
      - image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
        name: kube-rbac-proxy
        args: ["--secure-listen-address=0.0.0.0:8443", "--upstream=http://127.0.0.1:8080/", "--logtostderr=true", "--v=10"]
        ports:
        - containerPort: {{ .Values.service.port }}
          name: {{ .Values.service.targetPorts }}
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: manager
        args: [
          "--metrics-addr=127.0.0.1:8080",
          {{- if .Values.deployment.args.enableLeaderElection }}
          "--enable-leader-election",
          {{- end }}
          {{- if .Values.deployment.args.disableApprovalCheck }}
          ---disable-approval-check,
          {{- end }}
        ]
        command: ["/manager"]
        {{- if .Values.tunnel.enabled }}
        env:
          - name: STEP_TLS_TUNNEL
            value: /opt/config/tunnel.json
        {{- end }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        {{- if .Values.tunnel.enabled }}
        volumeMounts:
          - name: tunnel-config
            mountPath: /opt/config
            readOnly: true
          - name: tunnel-tls
            mountPath: /opt/tunnel
            readOnly: true
        {{- end }}
      {{- if .Values.tunnel.enabled }}
      volumes:
      - name: tunnel-config
        configMap:
          name: {{ include "step-issuer.fullname" . }}-tunnel
      - name: tunnel-tls
        secret:
          secretName: {{ .Values.tunnel.secretName }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
