apiVersion: v1
kind: Service
metadata:
  name: "{{ template "step-issuer.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/port: "{{ .Values.service.ports }}"
    prometheus.io/scheme: "{{ .Values.service.targetPorts }}"
    prometheus.io/scrape: "{{ .Values.service.scrape }}"
  labels:
    control-plane: {{ .Values.service.controlPlane }}
spec:
  ports:
  - name: {{ .Values.service.targetPorts }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPorts }}
  selector:
    control-plane: {{ .Values.service.controlPlane }}
